In [2]:
import pandas as pd
import seaborn as sns 
import numpy as np 
import matplotlib.pyplot as plt  

%matplotlib  inline

In [3]:
df=pd.read_csv("S:\\NRTI SM\\PIRPLE\\Data-Mining-With-Python-master\\data.csv")

In [4]:
df.shape

(32941, 12)

In [5]:
df.head(15)

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
0,#country+name,#country+code,#date,#total+vaccinations,NaN,NaN,NaN,#total+vaccinations+daily,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,2021-02-22,0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN
2,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0
3,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0
4,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0
5,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0
6,Afghanistan,AFG,2021-02-27,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0
7,Afghanistan,AFG,2021-02-28,8200,8200.0,NaN,NaN,1367,0.02,0.02,NaN,35.0
8,Afghanistan,AFG,2021-03-01,NaN,NaN,NaN,NaN,1580,NaN,NaN,NaN,41.0
9,Afghanistan,AFG,2021-03-02,NaN,NaN,NaN,NaN,1794,NaN,NaN,NaN,46.0
10,Afghanistan,AFG,2021-03-03,NaN,NaN,NaN,NaN,2008,NaN,NaN,NaN,52.0
11,Afghanistan,AFG,2021-03-04,NaN,NaN,NaN,NaN,2221,NaN,NaN,NaN,57.0
12,Afghanistan,AFG,2021-03-05,NaN,NaN,NaN,NaN,2435,NaN,NaN,NaN,63.0
13,Afghanistan,AFG,2021-03-06,NaN,NaN,NaN,NaN,2649,NaN,NaN,NaN,68.0
14,Afghanistan,AFG,2021-03-07,NaN,NaN,NaN,NaN,2862,NaN,NaN,NaN,74.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32941 entries, 0 to 32940
Data columns (total 12 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   location                             32941 non-null  object
 1   iso_code                             32941 non-null  object
 2   date                                 32941 non-null  object
 3   total_vaccinations                   19348 non-null  object
 4   people_vaccinated                    18497 non-null  float64
 5   people_fully_vaccinated              15498 non-null  float64
 6   daily_vaccinations_raw               16340 non-null  float64
 7   daily_vaccinations                   32690 non-null  object
 8   total_vaccinations_per_hundred       19347 non-null  float64
 9   people_vaccinated_per_hundred        18497 non-null  float64
 10  people_fully_vaccinated_per_hundred  15498 non-null  float64
 11  daily_vaccinations_per_million       32689 non-null  float64
dtypes: float64(7), object(5)
memory usage: 3.0+ MB

In [7]:
df['date']=pd.to_datetime(df.date)

ValueError: ('Unknown string format:', '#date')

In [9]:
df.drop([0], axis=0).head(5)

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
1,Afghanistan,AFG,2021-02-22,0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN
2,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0
3,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0
4,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0
5,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0

In [10]:
df['date']=pd.to_datetime(df.date)

ValueError: ('Unknown string format:', '#date')

In [11]:
df1=df.drop([0], axis=0).head(5)

In [12]:
df1.head()

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
1,Afghanistan,AFG,2021-02-22,0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN
2,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0
3,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0
4,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0
5,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0

In [13]:
df1['date']=pd.to_datetime(df1.date)

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 1 to 5
Data columns (total 12 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   location                             5 non-null      object
 1   iso_code                             5 non-null      object
 2   date                                 5 non-null      datetime64[ns]
 3   total_vaccinations                   1 non-null      object
 4   people_vaccinated                    1 non-null      float64
 5   people_fully_vaccinated              0 non-null      float64
 6   daily_vaccinations_raw               0 non-null      float64
 7   daily_vaccinations                   4 non-null      object
 8   total_vaccinations_per_hundred       1 non-null      float64
 9   people_vaccinated_per_hundred        1 non-null      float64
 10  people_fully_vaccinated_per_hundred  0 non-null      float64
 11  daily_vaccinations_per_million       4 non-null      float64
dtypes: datetime64[ns](1), float64(7), object(4)
memory usage: 520.0+ bytes

In [19]:
df1['Weekday']=df1.date.dt.weekday
#Looking for weekdays in the date.
#Monday to Sunday numbered as 0 to 6

In [20]:
df1.head(5)

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,Weekday
1,Afghanistan,AFG,2021-02-22,0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,0
2,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0,1
3,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0,2
4,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0,3
5,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367,NaN,NaN,NaN,35.0,4